name: example-app

image:
  repository: errm/example
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: null

deployment:
  replicas: 1

service:
  type: ClusterIP

cron:
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  concurrencyPolicy: Allow

hookJob:
  hook: pre-install,pre-upgrade
  weight: 10
  deletePolicy: hook-succeeded,hook-failed

resources:
  limits:
    memory: "256Mi"
    cpu: "250m"

components: {}
env: {}
