apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubeslate.fullname" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kubeslate.fullname" . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kubeslate.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubeslate.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "kubeslate.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
